---
- name: Instalar e configurar Apache no RHEL 9
  hosts: all
  become: true
  tasks:
    - name: Garantir que o Apache (httpd) esteja instalado
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Habilitar e iniciar o serviço do Apache
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: Copiar arquivo de configuracao httpd.conf
      ansible.builtin.copy:
        src: files/httpd.conf
        dest: /etc/httpd/conf/httpd.conf
        owner: root
        group: root
        mode: '0664'

    - name: Copiar página simples index.html
      ansible.builtin.copy:
        src: files/index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0664'

    - name: Permitir HTTP no firewalld (porta 80)
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true
      ignore_errors: true
      # when: ansible_facts.services["firewalld.service"] is defined

    - name: Verificar HTTP 200 na porta 80 (localhost)
      ansible.builtin.uri:
        url: "http://{{ ansible_default_ipv4.address }}"
        status_code: 200
        return_content: false
        timeout: 5
      register: http_check
      retries: 10
      delay: 3
      until: http_check.status == 200
      changed_when: false
